"""Add currency and salary_period to JobOffer and update UserPreference

Revision ID: df8e4d9ef8fd
Revises: d4c2df74d039
Create Date: 2026-05-14 12:02:21.435150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'df8e4d9ef8fd'
down_revision: Union[str, Sequence[str], None] = 'd4c2df74d039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_offers', sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('job_offers', sa.Column('salary_period', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute("UPDATE job_offers SET currency = 'PLN', salary_period = 'monthly'")
    op.alter_column('job_offers', 'currency', nullable=False)
    op.alter_column('job_offers', 'salary_period', nullable=False)
    
    op.add_column('userpreference', sa.Column('min_preferred_salary', sa.Numeric(), nullable=True))
    op.add_column('userpreference', sa.Column('max_preferred_salary', sa.Numeric(), nullable=True))
    op.add_column('userpreference', sa.Column('preferred_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('userpreference', sa.Column('preferred_working_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('userpreference', sa.Column('preferred_location', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('userpreference', sa.Column('preferred_tech_stack', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('userpreference', sa.Column('preferred_salary_period', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userpreference', 'preferred_salary_period')
    op.drop_column('userpreference', 'preferred_tech_stack')
    op.drop_column('userpreference', 'preferred_location')
    op.drop_column('userpreference', 'preferred_working_mode')
    op.drop_column('userpreference', 'preferred_currency')
    op.drop_column('userpreference', 'max_preferred_salary')
    op.drop_column('userpreference', 'min_preferred_salary')
    op.drop_column('job_offers', 'salary_period')
    op.drop_column('job_offers', 'currency')
    # ### end Alembic commands ###
